name 'diabol-logrotate'
version '1.1.2'
source 'https://github.com/diabol/puppet-logrotate'
license 'MIT'
summary 'Logrotate module'
description 'Manage logrotate on your servers with Puppet'
project_page 'https://github.com/diabol/puppet-logrotate'
